### ISSUE TITLE
[Question] Why special case for dtype=np.float64 in __init__ and clear ?

### ISSUE THREAD

**Issue by GilShoshan94** [Dennis-van-Gils/python-dvg-ringbuffer#1]
Hi @Dennis-van-Gils.

Amazing ring buffer !
I am studying your code and don't understand why do you have a special treatment for np.float64.

It is only in the [`__init__`](https://github.com/Dennis-van-Gils/python-dvg-ringbuffer/blob/master/src/dvg_ringbuffer.py#L189) and [`clear`](https://github.com/Dennis-van-Gils/python-dvg-ringbuffer/blob/master/src/dvg_ringbuffer.py#L212) methods.

I would guess you are doing that to optimize your array creation (and reset) with np.nan which should be faster than setting the whole array to zeros.

But I failed to understand why it is only for dtype=np.float64.

Could you explain please ?

**Comment by Dennis-van-Gils** [comment]
Hi Gil,
I'm glad you like my work and I hope it can be of help to you.

I'm initializing float64 arrays to `np.nan`, because it is my preference above setting it to `0.0`. If I could initialize integer arrays to `np.nan`, I would. But as you might know, `np.nan` is a special float64 representation only and does not exist for integer types.

Speed is not my concern here. The beauty of initializing the array to `np.nan` is that subsequent scipy or numpy operations (like mean, standard deviation, fourier transform, correlation, etc, etc) will work just fine and return a physically correct value, useful when the input array was not fully populated yet. Also, for a physicist like myself ;), np.nan is exactly what an uninitialized element should be: *Not a number*. Not `0.0`, which is indistinguishable from an added intended zero.

Say, `array=[2., 4., 7., 0., 0.]` which was init to zeros and only the first 3 elements got populated:
  ``np.mean([2, 4, 7, 0, 0]) = 2.6``
This is physically incorrect. The zeros should not have been taken into account.

Now, `array=[2., 4., 7., np.nan, np.nan]`, which was init to `np.nan` and only the first 3 elements got populated:
  ``np.mean([2, 4, 7, np.nan, np.nan]) = np.nan``
We at least know the array was not completely populated yet as it returned `np.nan`. Or...
  ``np.nanmean([2, 4, 7, np.nan, np.nan]) = 4.333``
Great! We have a physically meaningful value on an incompletely populated array.

I hope I made it clear. Good luck with your project

Best regards,
Dennis

**Comment by GilShoshan94** [comment]
Thank you for your explanation.
This is great.

I didn't know  np.nan is a special float64 representation only and does not exist for integer types.

I will try to find a workaround as I want different dtype of ring buffer and also integer and want also the subsequent scipy or numpy operations (like mean, ...) to work correctly.

If I find something, I will post a reply here to contribute back to you.

Thank you.

**Comment by Dennis-van-Gils** [comment]
I just realize that my ringbuffer implementation will always return an array with a size corresponding to the currently populated elements. It will never return the full reserved and not-yet-fully populated array padded with either zeros or np.nans. Hence, the explanation I gave above still holds true, but is not of concern to the user. For me, the debugger and code-maintainer, the np.nan values in the reserved array are very handy when debugging.

So, you don't have to go hunt for a work-around as the problem does not exist for you in the first place :)

**Comment by Dennis-van-Gils** [comment]
Btw. If, for whatever reason, you still want to implement a special case for integer-type values denoting nan, be aware that the contiguous C-style array expects **each** element to be of the same byte size. You might be tempted to use `None`, but this is represented in python as a 16 byte object. ``None.__sizeof__()`` returns 16. When sticking to an int16-type array it might work. (Untested. Also, numpy/scipy operations on `None` elements are not supported, so you would have to filter out these `None` elements in your own code before passing them to numpy/scipy). int32 or int64-type arrays will go haywire if you intermix them with `None` elements.

**Comment by GilShoshan94** [comment]
I am aware of C-style array and I guess that's why Numpy does not have a NAN for int but does for float.
I was actually trying to check if the buffer always return an array with the size of only the data inside and indeed it is :).
This was the workaround I was thinking of.

I am still studying your code and didn't start to use it yet (doing a real time spectrogram).

If I found a bug (but I doubt as your code looks rock solid) I will open a issue.

Thank you for confirming  that the problem does not exist for the end user.

**Comment by Dennis-van-Gils** [comment]
| `doing a real time spectrogram`
Nice. Great usage for a ring buffer. Perhaps the following code can be of use to you as well. It is my speed-oriented https://pypi.org/project/pyFFTW/ implementation of a Welch powerspectrum which I also use for real-time analysis in conjunction with my ringbuffer. See https://github.com/Dennis-van-Gils/python-dvg-dump/blob/master/src/dvg_fftw_welchpowerspectrum.py. It is not yet turned into a proper PyPi package with configurable parameters. Still hope to get around to that one of these years, haha. Feel free to fork.
